# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               info@
tagline:             <a href="http://waterlooregion.org">waterlooregion.org</a>
description:         "Open Data and Open Source from the Social Planning Council"
url:                 http://info.waterlooregion.org
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Todd Turnbull
  url:               http://waterlooregion.org
  email:             info@waterlooregion.org

# Custom vars
version:             1.0.0
