# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           pretty

# Setup
title:               info@waterlooregion.org
tagline:             "Open Data and Open Source from the Social Development Centre"
description:         "Open Data and Open Source from the Social Development Centre"
url:                 http://info.waterlooregion.org
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Todd Turnbull
  url:               http://waterlooregion.org
  email:             info@waterlooregion.org

# Custom vars
version:             1.0.0
